/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/Bridge Gate.glb -o src/components/Bridge.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from "@react-three/cannon";

export function Bridge(props) {
  const { nodes, materials } = useGLTF('/assets/models/Bridge Gate.glb')
  const [ref, api] = useBox(() => ({ mass: 1, position: [0, 0.5, -0.031] }));

  return (
    <group position={[0, 0.5, -0.031]} rotation={[1.6, 0, 0]} scale={3}>
      <group scale={100}>
        <mesh geometry={nodes.Bridge002_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Bridge002_2.geometry} material={materials.LightWood} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Bridge Gate.glb')
