/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/PoliceCar.glb -o src/components/CarModel.jsx -r public/ 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CarModel() {
  const { nodes, materials } = useGLTF('/assets/models/PoliceCar.glb')
  return (
    <group rotation={[0, Math.PI, 0]} scale={[0.34,0.32,0.4]} position={[0,-0.13,-0.02]}>
      <group position={[-0.001, 0.5, -0.031]} rotation={[0, -70.7, 0]} scale={0.6}>
        <mesh geometry={nodes.PUSHILIN_Police_car_Cube006.geometry} material={materials.police_car} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/PoliceCar.glb')
